# Generated by Django 2.2.12 on 2020-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, choices=[('collectstatic', 'Collectstatic'), ('loaddata', 'Loaddata')], help_text='Select management command', max_length=100, null=True)),
                ('arg', models.CharField(blank=True, help_text='Enter argument if any', max_length=100, null=True)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('output', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Run Management Command',
            },
        ),
    ]
